export const DB_TYPE = 'DB_TYPE'
export const DB_HOST = 'DB_HOST'
export const DB_PORT = 'DB_PORT'
export const DB_USERNAME = 'DB_USERNAME'
export const DB_PWD = 'DB_PWD'
export const DB_NAME = 'DB_NAME'
