export const PAYMENT_REQUEST_TOPIC_NAME = 'PAYMENT_REQUEST_TOPIC_NAME'
export const PAYMENT_RESPONSE_TOPIC_NAME = 'PAYMENT_RESPONSE_TOPIC_NAME'
export const PAYMENT_GROUP_ID = 'PAYMENT_GROUP_ID'

export const RESTAURANT_APPROVAL_REQUEST_TOPIC_NAME = 'RESTAURANT_APPROVAL_REQUEST_TOPIC_NAME'
export const RESTAURANT_APPROVAL_RESPONSE_TOPIC_NAME = 'RESTAURANT_APPROVAL_RESPONSE_TOPIC_NAME'
export const RESTAURANT_GROUP_ID = 'RESTAURANT_GROUP_ID'


